// <auto-generated />
using System;
using BTL_WEBDEV2025.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL_WEBDEV2025.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107150836_ChangeOrderDetailToProductVariantId")]
    partial class ChangeOrderDetailToProductVariantId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Balenciaga"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Louboutin"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 6,
                            Name = "New Balance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ASICS"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Reebok"
                        });
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Women"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kid"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Unisex"
                        });
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecialDeal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 4,
                            Description = "Classic leather and heritage style.",
                            ImageUrl = "/images/products/nike_airforce1.jpg",
                            IsFeatured = true,
                            IsSpecialDeal = false,
                            Name = "Nike Air Force 1 '07",
                            Price = 110m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Big Air unit comfort.",
                            DiscountPrice = 120m,
                            ImageUrl = "/images/products/nike_airmax270.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = true,
                            Name = "Nike Air Max 270",
                            Price = 150m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 4,
                            Description = "Street icon returns with retro colors.",
                            ImageUrl = "/images/products/nike_dunklow.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Nike Dunk Low Retro",
                            Price = 100m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Everyday responsive running shoes.",
                            ImageUrl = "/images/products/nike_pegasus40.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Nike Air Zoom Pegasus 40",
                            Price = 130m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 4,
                            Description = "Retro basketball-inspired design.",
                            ImageUrl = "/images/products/nike_blazer.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Nike Blazer Mid '77",
                            Price = 110m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Training stability and grip.",
                            ImageUrl = "/images/products/nike_metcon9.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Nike Metcon 9",
                            Price = 140m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "Natural feel with lightweight support.",
                            ImageUrl = "/images/products/nike_freerun.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Nike Free Run 5.0",
                            Price = 120m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Giannis signature shoe.",
                            ImageUrl = "/images/products/nike_freak5.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Nike Zoom Freak 5",
                            Price = 135m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            CategoryId = 4,
                            Description = "Inspired by '90s streetwear.",
                            ImageUrl = "/images/products/nike_huarache.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Nike Air Huarache",
                            Price = 125m
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Super fast race-day running shoes.",
                            ImageUrl = "/images/products/nike_vaporfly3.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Nike Vaporfly 3",
                            Price = 250m
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            CategoryId = 2,
                            Description = "Comfort and energy return.",
                            ImageUrl = "/images/products/adidas_ultraboost1.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Adidas Ultraboost 1.0",
                            Price = 180m
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "Timeless tennis silhouette.",
                            ImageUrl = "/images/products/adidas_stansmith.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Adidas Stan Smith",
                            Price = 95m
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "Iconic shell-toe sneaker.",
                            ImageUrl = "/images/products/adidas_superstar.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Adidas Superstar",
                            Price = 90m
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Urban comfort meets modern tech.",
                            ImageUrl = "/images/products/adidas_nmdr1.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Adidas NMD_R1",
                            Price = 150m
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "Retro indoor soccer classic.",
                            ImageUrl = "/images/products/adidas_samba.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Adidas Samba OG",
                            Price = 100m
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 3,
                            CategoryId = 4,
                            Description = "Chunky sneaker trendsetter.",
                            ImageUrl = "/images/products/balenciaga_triples.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Balenciaga Triple S",
                            Price = 950m
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 3,
                            CategoryId = 2,
                            Description = "Sock-like futuristic silhouette.",
                            ImageUrl = "/images/products/balenciaga_speed.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Balenciaga Speed 2.0",
                            Price = 850m
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 3,
                            CategoryId = 4,
                            Description = "Technical, layered trail sneaker.",
                            ImageUrl = "/images/products/balenciaga_track.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Balenciaga Track",
                            Price = 895m
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Oversized sole futuristic design.",
                            ImageUrl = "/images/products/balenciaga_defender.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Balenciaga Defender",
                            Price = 1100m
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 4,
                            CategoryId = 2,
                            Description = "Signature red sole and spikes.",
                            ImageUrl = "/images/products/louboutin_vieira.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Louboutin Vieira Spikes",
                            Price = 850m
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Luxury leather low-top sneakers.",
                            ImageUrl = "/images/products/louboutin_louis.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Louboutin Louis Junior",
                            Price = 995m
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 5,
                            CategoryId = 4,
                            Description = "Retro-futuristic design.",
                            ImageUrl = "/images/products/puma_rsx.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Puma RS-X",
                            Price = 120m
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            CategoryId = 4,
                            Description = "Timeless streetwear sneaker.",
                            ImageUrl = "/images/products/puma_suede.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Puma Suede Classic",
                            Price = 80m
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 5,
                            CategoryId = 1,
                            Description = "Comfort with vintage look.",
                            ImageUrl = "/images/products/puma_futurerider.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Puma Future Rider",
                            Price = 90m
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 5,
                            CategoryId = 2,
                            Description = "Bold sole, soft leather upper.",
                            ImageUrl = "/images/products/puma_cali.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Puma Cali Dream",
                            Price = 100m
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 6,
                            CategoryId = 4,
                            Description = "Revived '80s basketball icon.",
                            ImageUrl = "/images/products/nb_550.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "New Balance 550",
                            Price = 110m
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 6,
                            CategoryId = 1,
                            Description = "Premium running performance.",
                            ImageUrl = "/images/products/nb_990v6.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "New Balance 990v6",
                            Price = 200m
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 6,
                            CategoryId = 1,
                            Description = "Max comfort daily runner.",
                            ImageUrl = "/images/products/nb_1080v13.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "New Balance Fresh Foam X 1080v13",
                            Price = 160m
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 6,
                            CategoryId = 4,
                            Description = "Retro running-inspired lifestyle shoe.",
                            ImageUrl = "/images/products/nb_327.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "New Balance 327",
                            Price = 120m
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 7,
                            CategoryId = 1,
                            Description = "Stability with premium comfort.",
                            ImageUrl = "/images/products/asics_kayano30.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "ASICS Gel-Kayano 30",
                            Price = 160m
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 7,
                            CategoryId = 2,
                            Description = "Cushioning and cloud-like ride.",
                            ImageUrl = "/images/products/asics_nimbus26.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "ASICS Gel-Nimbus 26",
                            Price = 170m
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 7,
                            CategoryId = 1,
                            Description = "Everyday running reliability.",
                            ImageUrl = "/images/products/asics_gt2000.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "ASICS GT-2000 12",
                            Price = 150m
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 8,
                            CategoryId = 4,
                            Description = "Clean retro court sneaker.",
                            ImageUrl = "/images/products/reebok_clubc85.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Reebok Club C 85",
                            Price = 85m
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 8,
                            CategoryId = 4,
                            Description = "Heritage style and soft leather.",
                            ImageUrl = "/images/products/reebok_classic.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Reebok Classic Leather",
                            Price = 90m
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 8,
                            CategoryId = 1,
                            Description = "Functional training shoe.",
                            ImageUrl = "/images/products/reebok_nanox4.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Reebok Nano X4",
                            Price = 140m
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 8,
                            CategoryId = 2,
                            Description = "Energy-return performance sneaker.",
                            ImageUrl = "/images/products/reebok_zig.jpg",
                            IsFeatured = false,
                            IsSpecialDeal = false,
                            Name = "Reebok Zig Kinetica 2.5",
                            Price = 130m
                        });
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "White",
                            ProductId = 1,
                            Size = "41",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 2,
                            Color = "White",
                            ProductId = 1,
                            Size = "42",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black",
                            ProductId = 1,
                            Size = "42",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 4,
                            Color = "Red/Black",
                            ProductId = 2,
                            Size = "42",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 5,
                            Color = "Blue/White",
                            ProductId = 2,
                            Size = "43",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 6,
                            Color = "Panda",
                            ProductId = 3,
                            Size = "40",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 7,
                            Color = "Panda",
                            ProductId = 3,
                            Size = "41",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 8,
                            Color = "Black",
                            ProductId = 4,
                            Size = "41",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 9,
                            Color = "Black",
                            ProductId = 4,
                            Size = "42",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 10,
                            Color = "White/Red",
                            ProductId = 5,
                            Size = "42",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 11,
                            Color = "White/Red",
                            ProductId = 5,
                            Size = "43",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 12,
                            Color = "Grey/Volt",
                            ProductId = 6,
                            Size = "43",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 13,
                            Color = "Pink Foam",
                            ProductId = 7,
                            Size = "38",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 14,
                            Color = "Pink Foam",
                            ProductId = 7,
                            Size = "39",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 15,
                            Color = "Blue/Gold",
                            ProductId = 8,
                            Size = "44",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 16,
                            Color = "Black/White",
                            ProductId = 9,
                            Size = "40",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 17,
                            Color = "Triple Black",
                            ProductId = 9,
                            Size = "41",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 18,
                            Color = "White/Red",
                            ProductId = 10,
                            Size = "42",
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 19,
                            Color = "Cloud White",
                            ProductId = 11,
                            Size = "37",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 20,
                            Color = "Cloud White",
                            ProductId = 11,
                            Size = "38",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 21,
                            Color = "White/Green",
                            ProductId = 12,
                            Size = "41",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 22,
                            Color = "White/Green",
                            ProductId = 12,
                            Size = "42",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 23,
                            Color = "White/Black",
                            ProductId = 13,
                            Size = "40",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 24,
                            Color = "White/Black",
                            ProductId = 13,
                            Size = "41",
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 25,
                            Color = "Core Black",
                            ProductId = 14,
                            Size = "42",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 26,
                            Color = "White/Black",
                            ProductId = 15,
                            Size = "39",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 27,
                            Color = "White/Black",
                            ProductId = 15,
                            Size = "40",
                            StockQuantity = 38
                        },
                        new
                        {
                            Id = 28,
                            Color = "Beige",
                            ProductId = 16,
                            Size = "41",
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 29,
                            Color = "Black",
                            ProductId = 16,
                            Size = "42",
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 30,
                            Color = "Black/White",
                            ProductId = 17,
                            Size = "38",
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 31,
                            Color = "Grey/Blue",
                            ProductId = 18,
                            Size = "42",
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 32,
                            Color = "Black",
                            ProductId = 19,
                            Size = "43",
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 33,
                            Color = "White/Silver",
                            ProductId = 20,
                            Size = "37",
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 34,
                            Color = "Black",
                            ProductId = 21,
                            Size = "42",
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 35,
                            Color = "Navy",
                            ProductId = 21,
                            Size = "43",
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 36,
                            Color = "Grey/Yellow",
                            ProductId = 22,
                            Size = "41",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 37,
                            Color = "Black/White",
                            ProductId = 23,
                            Size = "40",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 38,
                            Color = "Red/White",
                            ProductId = 23,
                            Size = "41",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 39,
                            Color = "Blue/Orange",
                            ProductId = 24,
                            Size = "42",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 40,
                            Color = "White/Pink",
                            ProductId = 25,
                            Size = "38",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 41,
                            Color = "White/Green",
                            ProductId = 26,
                            Size = "41",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 42,
                            Color = "White/Grey",
                            ProductId = 26,
                            Size = "42",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 43,
                            Color = "Grey",
                            ProductId = 27,
                            Size = "42.5",
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 44,
                            Color = "Grey",
                            ProductId = 27,
                            Size = "43",
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 45,
                            Color = "White/Blue",
                            ProductId = 28,
                            Size = "42",
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 46,
                            Color = "Multi",
                            ProductId = 29,
                            Size = "39",
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 47,
                            Color = "Navy/Orange",
                            ProductId = 29,
                            Size = "40",
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 48,
                            Color = "Black/Lime",
                            ProductId = 30,
                            Size = "42",
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 49,
                            Color = "Black/Lime",
                            ProductId = 30,
                            Size = "43",
                            StockQuantity = 11
                        },
                        new
                        {
                            Id = 50,
                            Color = "Pink/Blue",
                            ProductId = 31,
                            Size = "38",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 51,
                            Color = "Blue/Orange",
                            ProductId = 32,
                            Size = "41.5",
                            StockQuantity = 13
                        },
                        new
                        {
                            Id = 52,
                            Color = "White/Green",
                            ProductId = 33,
                            Size = "40",
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 53,
                            Color = "White/Green",
                            ProductId = 33,
                            Size = "41",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 54,
                            Color = "White/Gum",
                            ProductId = 34,
                            Size = "42",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 55,
                            Color = "Black/Red",
                            ProductId = 35,
                            Size = "43",
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 56,
                            Color = "Purple/Pink",
                            ProductId = 36,
                            Size = "37",
                            StockQuantity = 11
                        });
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingPreference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@nike.com",
                            FullName = "Admin Account",
                            PasswordHash = "admin123",
                            PhoneNumber = "123456",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Order", b =>
                {
                    b.HasOne("BTL_WEBDEV2025.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.OrderDetail", b =>
                {
                    b.HasOne("BTL_WEBDEV2025.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTL_WEBDEV2025.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Product", b =>
                {
                    b.HasOne("BTL_WEBDEV2025.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("BTL_WEBDEV2025.Models.Category", "CategoryRef")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Brand");

                    b.Navigation("CategoryRef");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.ProductVariant", b =>
                {
                    b.HasOne("BTL_WEBDEV2025.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.User", b =>
                {
                    b.HasOne("BTL_WEBDEV2025.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("BTL_WEBDEV2025.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
